"""adds Author model

Revision ID: c9aaee3db94b
Revises: 8cc705bc90a8
Create Date: 2025-05-06 11:36:55.625777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9aaee3db94b'
down_revision = '8cc705bc90a8'
branch_labels = None
depends_on = None


# def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('author', schema=None) as batch_op:
#         batch_op.alter_column('id',
#                existing_type=sa.INTEGER(),
#                server_default=None,
#                existing_nullable=False,
#                autoincrement=True)
#         batch_op.alter_column('name',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=False)
       
# ### end Alembic commands ###
       # ***************************************************
       #             From GPT debugging
       # ***************************************************
def upgrade():
       # ### commands auto generated by Alembic - please adjust! ###
       with op.batch_alter_table('author', schema=None) as batch_op:
              batch_op.alter_column('name',
                     existing_type=sa.VARCHAR(length=100),
                     nullable=False)  # Set 'name' column as NOT NULL

       # ### end Alembic commands ###


def downgrade():
       # ### commands auto generated by Alembic - please adjust! ###
       with op.batch_alter_table('author', schema=None) as batch_op:
              batch_op.alter_column('name',
                     existing_type=sa.VARCHAR(length=100),
                     nullable=True)
       #  batch_op.alter_column('id',
       #         existing_type=sa.INTEGER(),
       #         server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
       #         existing_nullable=False,
       #         autoincrement=True)

       # ### end Alembic commands ###
